spring:
  kafka:
    bootstrap-servers: kafka:9092
  profiles:
    active: spring-kafka #apache-kafka

app:
  kafka:
    kafkaConfirmationCodeTopic: "confirmation-code"
    kafkaRegistrationRequestListener: "registration-request"
    kafkaEventGroupId: "kafka-auth-group-id"