spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: kafka:9092
  redis:
    host: redis
    port: 6379
  profiles:
    active: spring-kafka #apache-kafka

token:
  signing:
    key: secretKeySecretKeySecretKeySecretKeySecretKey

app:
  kafka:
    kafkaRegistrationTopic: "registration-request"
    kafkaConfirmationCodeListener: "confirmation-code"
    kafkaEventGroupId: "kafka-auth-group-id"

server:
  port: 8000